### ISSUE TITLE
Node Version needs to be bumped up to supported versions

### ISSUE THREAD

**Issue by brocktriplets** [tkikuchi2000/mkdocs-firebase-pipeline#1]
Please update the Node JS Version to minimum supported versions, at least 10+, but 12 would be great.

Thanks!

**Comment by tkikuchi2000** [comment]
Sorry for the late comment.

The supported node versions have been updated.
If your environment is node12, please specify the tag `mkdocs-firebase-pipeline:node12-alpine`.
